'''Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''




from collections import Counter
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        if len(s) < len(t):
            r = t
            t = s
            s = r
        a = dict(Counter(s))
        b = dict(Counter(t))
        try:
            for i in a:
                if a[i] != b[i]:
                    return i
                    break
        except KeyError:
            return i

b = Solution()
print b.findTheDifference("abcd","abcde")
